"""
Safety gate for Cypher generated by the Graph Explorer agent's LLM.

Local models (via Ollama) are meaningfully more likely than a hosted
frontier model to: wrap output in markdown fences, add explanatory prose
around the query, hallucinate a write operation when it "helpfully" tries
to fix data it thinks looks wrong, or chain multiple statements. This
module extracts the query and refuses to let anything but a single,
bounded, read-only MATCH...RETURN pass through to the database.

Nothing here is a substitute for running Neo4j with a least-privilege,
read-only DB user in any non-toy deployment — this is a defense-in-depth
layer on top of that, not instead of it.
"""
import re

# Case-insensitive, word-boundary matches for anything that mutates data or
# schema, or that could be used to do so via a procedure call.
_FORBIDDEN_KEYWORDS = [
    "CREATE", "MERGE", "DELETE", "DETACH", "SET", "REMOVE", "DROP",
    "CALL", "LOAD CSV", "FOREACH",
]
_FORBIDDEN_PATTERN = re.compile(
    r"\b(" + "|".join(re.escape(k) for k in _FORBIDDEN_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

_CODE_FENCE_PATTERN = re.compile(r"```(?:cypher|sql)?\s*(.*?)```", re.IGNORECASE | re.DOTALL)
_LIMIT_PATTERN = re.compile(r"\bLIMIT\s+\d+\b", re.IGNORECASE)


def extract_cypher(raw_text: str) -> str:
    """
    Pull the query out of an LLM response that may include markdown fences,
    explanatory prose, or trailing commentary. Falls back to the raw text
    (stripped) if no fence is found — small models often skip fences too.
    """
    fence_match = _CODE_FENCE_PATTERN.search(raw_text)
    candidate = fence_match.group(1) if fence_match else raw_text
    return candidate.strip()


def validate(cypher: str) -> tuple[bool, str]:
    """
    Returns (is_valid, reason). `reason` explains the rejection when
    is_valid is False, or is empty when True.
    """
    if not cypher or not cypher.strip():
        return False, "empty query"

    stripped = cypher.strip()

    # Reject multiple statements (semicolon-separated) — a common way a
    # destructive op hides after an innocent-looking read.
    # A single trailing semicolon is fine and gets stripped below.
    body = stripped[:-1] if stripped.endswith(";") else stripped
    if ";" in body:
        return False, "multiple statements are not allowed (found ';' mid-query)"

    if _FORBIDDEN_PATTERN.search(body):
        match = _FORBIDDEN_PATTERN.search(body)
        return False, f"forbidden keyword '{match.group(1).upper()}' — only read-only MATCH/RETURN is allowed"

    if not re.search(r"\bRETURN\b", body, re.IGNORECASE):
        return False, "query has no RETURN clause — read queries must return something"

    if not re.search(r"\bMATCH\b", body, re.IGNORECASE):
        return False, "query has no MATCH clause"

    return True, ""


def enforce_limit(cypher: str, default_limit: int = 100) -> str:
    """Append a LIMIT if the query doesn't already have one, to bound worst-case cost."""
    stripped = cypher.strip().rstrip(";")
    if _LIMIT_PATTERN.search(stripped):
        return stripped
    return f"{stripped}\nLIMIT {default_limit}"


def sanitize_and_validate(raw_llm_output: str, default_limit: int = 100) -> tuple[str | None, str]:
    """
    Full pipeline: extract -> validate -> enforce limit.
    Returns (safe_cypher_or_None, reason). safe_cypher is None on rejection.
    """
    cypher = extract_cypher(raw_llm_output)
    is_valid, reason = validate(cypher)
    if not is_valid:
        return None, reason
    return enforce_limit(cypher, default_limit), ""
